### PR TITLE
Add fuel tracking and consumption

### PR DESCRIPTION
**Pull request by stlsmiths**
Hello - I really like this little app and fondly remember playing the Atari game.   I thought that adding the "fuel state" feature was important from the original game so I forked this and added some logic for that.  The fuel state is updated in the ship.acceleration method and once it is zero it sets the engine level to zero, for no available thrust.

Thanks for your cool app and great demo of Two.js.

### CODE REVIEW

**Review by halaprop — CHANGES_REQUESTED** [review]
Thanks for your kind note and this contribution. I'm glad you share my nostalgia for the game!  Let's do it just as you suggest, except:

1. do the `fuelLevel` check before computing the acceleration vector ax,ay, a few lines above where you suggested it
2. also, the label can have regular chars for the sign

   ` this.fuelLabel = new Label('fuel', { label: 'fuel:', plusSign: '', minusSign: '-'  });`

I use a different repo for hosting the live demo, and will add this change here. This is my first time using GitHub for any sort of collaboration, so please let me know if I'm going about this incorrectly and apologies in advance.

**Comment by stlsmiths** [comment]
Awesome!   I don't use Github for collaboration either (just as code repository) so we are def newbies at this.  I made the suggestions you recommended and posted another commit which should still show in this pull request.  

BTW - Are you happy with the fuel consumption rate ?   It was a pure guess, I only tweaked it a few times but it seems to work pretty well.   We don't want it to be too easy.

If you are happy with it - I think you can "merge" the pull request and it will incorporate the changes from my repo into your master.

Or worst case - if you like the changes, you can just copy the few lines of code and update your repo.  I don't care about getting credit, as my stuff is pretty minor.

**Review by halaprop — APPROVED** [review]
Great add! Thank you!

**Comment by halaprop** [comment]
I just did an approve and merge (I think :-)).   More about the change: I contemplated fuel, too, but worried about a slippery slope of fuel bonuses on the pads, and points, etc. Your idea, a simple budget per flight, is just right. As for the size of the budget, I'll take your intuition over my own. I put a lot of effort into the fractal landscape, and spent a lot of infinite fuel flying around to evaluate it aesthetically. (Including, FYI, with enough fuel, you can fly around and _under_ the surface!). 

Let's see how we like it at 1k units, depleting as you suggest.  We can always add to it, or do something fancier around bonuses. 

Thanks again for taking the interest and suggesting the improvement!

**Comment by stlsmiths** [comment]
Great - I checked your public master and the changes are in it.  👍🏼

I was thinking it might be cool at some point to give a checkbox for "fuel usage" to turn off the fuel usage - to allow complete traversal of the landscape, but I will leave that idea.  I like the cleanliness of the UI as is.   When I get time I will try and figure out how you fractal'ed the landscape.

**Comment by halaprop** [comment]
Okay. Deployed to the demo environment at https://luniland.halabe.com

**Pull request merged**
